In [1]:
# Bài 3.1:
import numpy as np

print("Phiên bản NumPy hiện tại:", np.__version__)
print("Cấu hình chi tiết NumPy:")
np.show_config()


Phiên bản NumPy hiện tại: 2.3.4
Cấu hình chi tiết NumPy:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/si

c:\Users\HOANG MINH\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [2]:
#3.2
import numpy as np
arr = np.arange(10)
print("Mảng arr:", arr)
print("Kích thước mảng:", arr.shape)

arr_even = arr[arr % 2 == 0]
print("Các phần tử chẵn:", arr_even)

arr_odd = arr[arr % 2 == 1]
print("Các phần tử lẻ:", arr_odd)

arr_update = np.where(arr % 2 == 0, arr, arr * 100)
print("Mảng sau khi cập nhật:", arr_update)

Mảng arr: [0 1 2 3 4 5 6 7 8 9]
Kích thước mảng: (10,)
Các phần tử chẵn: [0 2 4 6 8]
Các phần tử lẻ: [1 3 5 7 9]
Mảng sau khi cập nhật: [  0 100   2 300   4 500   6 700   8 900]


In [3]:
#3.3
import numpy as np

arr_a = np.array([1,2,3,2,3,4,5,4,6])
arr_b = np.array([7,2,10,2,9,9,8,9,8])

arr_c = np.intersect1d(arr_a, arr_b)
print("Các phần tử có trong cả hai mảng:", arr_c)

arr_d = np.setdiff1d(arr_a, arr_b)
print("Phần tử chỉ có trong arr_a:", arr_d)

arr_f = np.array([2, 6, 9, 10, 3, 27, 8, 6, 25, 16])
arr_e = arr_f[(arr_f >= 5) & (arr_f < 10)]
print("Các phần tử trong khoảng [5,10):", arr_e)


Các phần tử có trong cả hai mảng: [2]
Phần tử chỉ có trong arr_a: [1 3 4 5 6]
Các phần tử trong khoảng [5,10): [6 9 8 6]


In [2]:

# BÀI 3.4

import numpy as np
#c1
zero_arr = np.zeros(10, dtype=int)
zero_arr[4] = 1  
print("Câu 1  zero_arr:", zero_arr, "\n")
#c2
arr_h = np.arange(10, 25)
print("Câu 2  arr_h:", arr_h)
print("Câu 2  arr_h đảo ngược:", arr_h[::-1], "\n")

#c3
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
print("Câu 3  arr_k:", arr_k)
print("Câu 3  arr_l (lọc bỏ phần tử 0):", arr_l, "\n")

#c4
arr_l_extended = np.append(arr_l, [10, 20])
print("Câu 4  arr_l_extended:", arr_l_extended, "\n")

#c5
arr_inserted = np.insert(arr_l_extended, 5, 100)
print("Câu 5  arr_inserted:", arr_inserted, "\n")

#c6
arr_deleted = np.delete(arr_inserted, [0, 1, 2])
print("Câu 6  arr_deleted (sau khi xóa index 0,1,2):", arr_deleted, "\n")


print("=== KẾT QUẢ TỔNG HỢP ===")
print("arr ban đầu:", arr_k)
print("arr sau các bước:", arr_deleted)


Câu 1  zero_arr: [0 0 0 0 1 0 0 0 0 0] 

Câu 2  arr_h: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Câu 2  arr_h đảo ngược: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10] 

Câu 3  arr_k: [1 2 0 8 2 0 1 3 0 5 0]
Câu 3  arr_l (lọc bỏ phần tử 0): [1 2 8 2 1 3 5] 

Câu 4  arr_l_extended: [ 1  2  8  2  1  3  5 10 20] 

Câu 5  arr_inserted: [  1   2   8   2   1 100   3   5  10  20] 

Câu 6  arr_deleted (sau khi xóa index 0,1,2): [  2   1 100   3   5  10  20] 

=== KẾT QUẢ TỔNG HỢP ===
arr ban đầu: [1 2 0 8 2 0 1 3 0 5 0]
arr sau các bước: [  2   1 100   3   5  10  20]


In [3]:
#3.5
import numpy as np

# --- 1. Đọc dữ liệu từ file ---
with open("heights_1.txt") as f:
    height_list = [float(x) for x in f.read().split()]
with open("weights_1.txt") as f:
    weight_list = [float(x) for x in f.read().split()]

# --- 2. Tạo array ---
arr_height = np.array(height_list)
arr_weight = np.array(weight_list)

print("Chiều cao (inch):", arr_height[:10])
print("Cân nặng (pound):", arr_weight[:10])

# --- 3. Đổi đơn vị ---
arr_height_m = arr_height * 0.0254   # inch → mét
arr_weight_kg = arr_weight * 0.453592  # pound → kg

# --- 4. Tính BMI ---
arr_bmi = arr_weight_kg / (arr_height_m ** 2)

# --- 5. Hiển thị một vài giá trị ---
print("\n5 giá trị BMI đầu tiên:", np.round(arr_bmi[:5], 2))

# --- 6. Lọc BMI ---
arr_bmi_low = arr_bmi[arr_bmi <= 21]
arr_bmi_high = arr_bmi[arr_bmi > 21]

print(f"\nSố cầu thủ BMI ≤ 21: {len(arr_bmi_low)}")
print(f"Số cầu thủ BMI > 21: {len(arr_bmi_high)}")

# --- 7. Tính thống kê ---
mean_height = np.mean(arr_height_m)
mean_weight = np.mean(arr_weight_kg)
mean_bmi = np.mean(arr_bmi)

print(f"\nChiều cao TB: {mean_height:.2f} m")
print(f"Cân nặng TB: {mean_weight:.2f} kg")
print(f"BMI TB: {mean_bmi:.2f}")

# --- 8. Tìm giá trị lớn nhất & nhỏ nhất ---
print(f"\nChiều cao lớn nhất: {arr_height_m.max():.2f} m")
print(f"Chiều cao nhỏ nhất: {arr_height_m.min():.2f} m")
print(f"Cân nặng lớn nhất: {arr_weight_kg.max():.2f} kg")
print(f"Cân nặng nhỏ nhất: {arr_weight_kg.min():.2f} kg")


FileNotFoundError: [Errno 2] No such file or directory: 'heights_1.txt'

In [5]:
import pandas as pd
import numpy as np
import os # Dùng để kiểm tra file tồn tại

# --- GIAI ĐOẠN 1: TRÍCH XUẤT DỮ LIỆU TỪ LINK WEB BẰNG PANDAS ---

# Link trang web chứa dữ liệu
url = "http://wiki.stat.ucla.edu/soc/index.php/SOCR_Data_MLB_HeightsWeights"
file_heights = "height_1.txt"
file_weights = "weight_1.txt"

print(f"Đang cố gắng đọc dữ liệu từ link: {url}\n")

try:
    # Pandas có thể đọc bảng HTML trực tiếp từ link
    # [0] nghĩa là lấy bảng (table) đầu tiên tìm thấy trên trang
    tables = pd.read_html(url)
    df = tables[0]

    print("--- Đọc dữ liệu web thành công ---")
    print("5 dòng dữ liệu đầu tiên trích xuất được:")
    print(df.head())
    print("-----------------------------------")

    # Lấy dữ liệu từ các cột "Height(Inches)" và "Weight(Pounds)"
    height_data = df["Height(Inches)"]
    weight_data = df["Weight(Pounds)"]

    # --- GIAI ĐOẠN 2: GHI DỮ LIỆU RA FILE TXT ---
    
    # Ghi file heights.txt
    # np.savetxt là cách nhanh để lưu 1 array/series vào file text
    np.savetxt(file_heights, height_data, fmt='%.2f')
    print(f"\nĐã ghi dữ liệu chiều cao vào file '{file_heights}'")

    # Ghi file weights.txt
    np.savetxt(file_weights, weight_data, fmt='%.2f')
    print(f"Đã ghi dữ liệu cân nặng vào file '{file_weights}'")

    # --- GIAI ĐOẠN 3: HOÀN THÀNH BÀI 3.5 BẰNG NUMPY ---
    
    print("\n--- BẮT ĐẦU GIẢI BÀI 3.5 ---")
    
    # 1. Tạo numpy array arr_height từ list height (đọc từ file)
    arr_height = np.loadtxt(file_heights)
    print("1. Array chiều cao (arr_height):")
    print(arr_height)

    # 2. Tạo numpy array arr_weight từ list weight (đọc từ file)
    arr_weight = np.loadtxt(file_weights)
    print("\n2. Array cân nặng (arr_weight):")
    print(arr_weight)
    
    print("\n--- HOÀN THÀNH ---")

except ImportError:
    print("LỖI: Cần cài đặt pandas và lxml.")
    print("Chạy lệnh: pip install pandas lxml")
except ConnectionError:
    print(f"LỖI: Không thể kết nối tới link. Kiểm tra lại Internet.")
except Exception as e:
    print(f"Đã xảy ra lỗi: {e}")
    print("Vui lòng kiểm tra lại link hoặc thư viện.")

Đang cố gắng đọc dữ liệu từ link: http://wiki.stat.ucla.edu/soc/index.php/SOCR_Data_MLB_HeightsWeights

LỖI: Cần cài đặt pandas và lxml.
Chạy lệnh: pip install pandas lxml


In [7]:
# BAI 3.6 - thao tac tren mang 2D
import numpy as np

def bai_3_6():
    # 1) array 3x3 True
    arr_true = np.full((3,3), True, dtype=bool)
    print("C1 arr_true:\n", arr_true)

    # 2) arr_1D -> arr_2D 3x3 then chuyển cột 1 <-> cột 3 và ngược lại
    arr_1D = np.arange(9)  # 0..8
    arr_2D = arr_1D.reshape((3,3))
    print("C2 arr_2D original:\n", arr_2D)
    arr_swap_cols = arr_2D.copy()
    arr_swap_cols[:, [0,2]] = arr_swap_cols[:, [2,0]]  # swap col0 & col2
    print("   after swapping col1 and col3:\n", arr_swap_cols)
    # swap back
    arr_swap_cols[:, [0,2]] = arr_swap_cols[:, [2,0]]
    print("   swapped back:\n", arr_swap_cols)

    # 3) từ arr_2D, chuyển hàng 1 sang hàng 2 và ngược lại (swap row0 & row1)
    arr_swap_rows = arr_2D.copy()
    arr_swap_rows[[0,1], :] = arr_swap_rows[[1,0], :]
    print("C3 after swapping row1 and row2:\n", arr_swap_rows)

    # 4) đảo ngược các dòng của arr_2D (reverse row order)
    arr_rev_rows = arr_2D[::-1, :]
    print("C4 reverse rows:\n", arr_rev_rows)

    # 5) từ arr_2D của câu 4, đảo ngược các cột (mirror horizontally)
    arr_rev_rows_cols = arr_rev_rows[:, ::-1]
    print("C5 reverse columns of previous:\n", arr_rev_rows_cols)

    # 6) tạo arr_2D_null có NaN, kiểm tra giá trị null?
    arr_2D_null = np.array([[1,2,3], [np.nan, 5, 6], [7, np.nan, 9]], dtype=float)
    has_null = np.isnan(arr_2D_null).any()
    print("C6 arr_2D_null:\n", arr_2D_null)
    print("   has any NaN?", has_null)

    # 7) thay NaN bằng 0
    arr_no_null = np.nan_to_num(arr_2D_null, nan=0.0)
    print("C7 arr_no_null (NaN->0):\n", arr_no_null)

    return {
        "arr_true": arr_true, "arr_2D": arr_2D, "arr_swap_cols": arr_swap_cols,
        "arr_swap_rows": arr_swap_rows, "arr_rev_rows": arr_rev_rows,
        "arr_rev_rows_cols": arr_rev_rows_cols, "arr_2D_null": arr_2D_null,
        "arr_no_null": arr_no_null
    }

if __name__ == "__main__":
    bai_3_6()


C1 arr_true:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
C2 arr_2D original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
   after swapping col1 and col3:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
   swapped back:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
C3 after swapping row1 and row2:
 [[3 4 5]
 [0 1 2]
 [6 7 8]]
C4 reverse rows:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]
C5 reverse columns of previous:
 [[8 7 6]
 [5 4 3]
 [2 1 0]]
C6 arr_2D_null:
 [[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]]
   has any NaN? True
C7 arr_no_null (NaN->0):
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]]


In [9]:
# BAI 3.7 - thao tac tren baseball_2D
import numpy as np
import os

def read_baseball_2d(filename="baseball_2D.txt"):
    if os.path.exists(filename):
        # giả sử file text: mỗi dòng 2 số (height inch, weight pounds) tách bởi space/comma
        data = np.loadtxt(filename, delimiter=None)
        return data
    # nếu không có file, tạo sample (200 x 2)
    np.random.seed(1)
    heights = 68 + np.random.randint(-6,7,size=200)  # inch
    weights = 170 + np.random.randint(-35,36,size=200)  # lbs
    return np.column_stack((heights, weights)).astype(float)

def bai_3_7():
    np_baseball = read_baseball_2d()
    print("np_baseball shape:", np_baseball.shape, "dtype:", np_baseball.dtype)

    # 2) in dòng thứ 50 (index 49) nếu có
    if np_baseball.shape[0] >= 50:
        print("Row 50:", np_baseball[49])
    else:
        print("Không có row 50 (dữ liệu ít).")

    # 3) tạo np_weight từ cột 2
    np_weight = np_baseball[:, 1]
    print("np_weight (first 10):", np_weight[:10])

    # 4) chiều cao vận động viên thứ 124 (index 123)
    if np_baseball.shape[0] >= 124:
        height_124 = np_baseball[123, 0]
        print("Height of athlete #124:", height_124)
    else:
        height_124 = None
        print("Không có athlete #124 trong dữ liệu mẫu.")

    # 5) trung bình chiều cao và cân nặng
    mean_height = np.mean(np_baseball[:, 0])
    mean_weight = np.mean(np_baseball[:, 1])
    print("Mean height (inch):", mean_height, "Mean weight (lbs):", mean_weight)

    # 6) nhận xét tương quan: tính hệ số tương quan Pearson
    corrcoef = np.corrcoef(np_baseball[:,0], np_baseball[:,1])[0,1]
    print("Correlation coefficient (height vs weight):", corrcoef)
    if corrcoef > 0.5:
        comment = "tương quan thuận mạnh"
    elif corrcoef > 0.2:
        comment = "tương quan thuận vừa phải"
    elif corrcoef > -0.2:
        comment = "không có tương quan mạnh (gần 0)"
    else:
        comment = "tương quan nghịch"
    print("Nhận xét:", comment)

    return {
        "np_baseball": np_baseball, "np_weight": np_weight,
        "height_124": height_124, "mean_height": mean_height,
        "mean_weight": mean_weight, "corrcoef": corrcoef
    }

if __name__ == "__main__":
    bai_3_7()


np_baseball shape: (0,) dtype: float64
Không có row 50 (dữ liệu ít).


C:\Users\HOANG MINH\AppData\Local\Temp\ipykernel_17464\3634388120.py:8: UserWarning: loadtxt: input contained no data: "baseball_2D.txt"
  data = np.loadtxt(filename, delimiter=None)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
# BAI 3.8 - trung binh height theo position
import numpy as np
import os

def bai_3_8():
    # Nếu có file positions.txt (mỗi dòng 1 vị trí phù hợp với np_baseball), đọc vào.
    # Nếu không có, giả lập positions cho dữ liệu mẫu 200 người.
    pos_file = "positions.txt"
    if os.path.exists(pos_file):
        with open(pos_file) as f:
            positions = [line.strip() for line in f if line.strip()]
        positions = np.array(positions)
        print("Đã đọc positions từ file.")
    else:
        # giả lập: sample positions: 'P','C','1B','2B','3B','SS','LF','CF','RF'
        sample_positions = ['P','C','1B','2B','3B','SS','LF','CF','RF']
        # tạo 200 positions ngẫu nhiên
        np.random.seed(2)
        positions = np.random.choice(sample_positions, size=200)
        print("Không có file positions -> dùng positions mẫu.")

    # cần heights tương ứng (dùng hàm read_baseball_2d ở trên nếu có)
    if os.path.exists("baseball_2D.txt"):
        data = np.loadtxt("baseball_2D.txt")
        heights = data[:,0]
    else:
        # tạo heights giống phần trước (200)
        np.random.seed(1)
        heights = (68 + np.random.randint(-6,7,size=200)).astype(float)

    # tính mean height theo position
    unique_pos = np.unique(positions)
    mean_by_pos = {}
    for p in unique_pos:
        mask = positions == p
        if np.any(mask):
            mean_by_pos[p] = float(np.mean(heights[mask]))
        else:
            mean_by_pos[p] = None

    print("Mean height by position:")
    for p, m in sorted(mean_by_pos.items()):
        print(f"  {p}: {m:.2f} inch" if m is not None else f"  {p}: None")

    return mean_by_pos

if __name__ == "__main__":
    bai_3_8()


In [11]:
import pandas as pd

# --- BÀI 3.9: LỌC VÀ SẮP XẾP DỮ LIỆU EURO 2012 ---

# Để code chạy được ngay mà không cần file,
# ta đọc dữ liệu trực tiếp từ 1 link online
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro_2012/Euro_2012_stats.csv'

# "Tạo data frame euro12" (Đọc file)
euro12 = pd.read_csv(url)
print("--- Đã đọc dữ liệu euro2012.csv ---")


# 1. In giá trị cột Goals
print("\n1. Giá trị cột 'Goals':")
print(euro12['Goals'])

# 2. Có bao nhiêu đội tham gia Euro2012?
# Lấy số hàng (mỗi hàng 1 đội)
num_teams = euro12.shape[0]
print(f"\n2. Số đội tham gia: {num_teams} đội")

# 3. In thông tin của Euro2012 (type, shape, danh sách cột)
print("\n3. Thông tin chung của Euro2012:")
print(f"   Kích thước (Shape): {euro12.shape}")
print(f"   Danh sách các cột: {euro12.columns.tolist()}")
print("   Thông tin chi tiết (Info):")
euro12.info()

# 4. Tạo 1 data frame mới discipline
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print("\n4. Data frame 'discipline' (5 dòng đầu):")
print(discipline.head())

# 5. Sắp xếp discipline
discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=False)
print("\n5. Discipline đã sắp xếp (Thẻ Đỏ, Thẻ Vàng giảm dần):")
print(discipline_sorted)

# 6. a) Tính trung bình Yellow Cards
avg_yellow_cards = euro12['Yellow Cards'].mean()
print(f"\n6. a) Số thẻ vàng trung bình: {avg_yellow_cards:.2f}")

# 6. b) Lọc các đội đã ghi hơn 6 bàn thắng
teams_over_6_goals = euro12[euro12['Goals'] > 6]
print("\n6. b) Các đội ghi hơn 6 bàn:")
print(teams_over_6_goals[['Team', 'Goals']])

# 7. In các đội mà tên bắt đầu bằng 'G'
teams_starting_G = euro12[euro12['Team'].str.startswith('G')]
print("\n7. Các đội có tên bắt đầu bằng 'G':")
print(teams_starting_G)

# 8. In 7 cột đầu của euro12
print("\n8. 7 cột đầu tiên (5 dòng đầu):")
print(euro12.iloc[:, :7].head())

# 9. In tất cả các cột, trừ 3 cột cuối
print("\n9. Tất cả các cột trừ 3 cột cuối (5 dòng đầu):")
print(euro12.iloc[:, :-3].head())

# 10. In các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards
selected_stats = euro12[['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']]
print("\n10. Các cột (Team, Goals, Shooting Accuracy, YC, RC):")
print(selected_stats)

# 11. In cột 'Team', 'Shooting Accuracy' của 'England', 'Italy', 'Russia'
teams_of_interest = ['England', 'Italy', 'Russia']
# Dùng .isin() để lọc các đội có trong list
result_11 = euro12[euro12['Team'].isin(teams_of_interest)]
print("\n11. Shooting Accuracy của Anh, Ý, Nga:")
print(result_11[['Team', 'Shooting Accuracy']])

HTTPError: HTTP Error 404: Not Found

In [12]:
import pandas as pd

# --- BÀI 3.9: LỌC VÀ SẮP XẾP DỮ LIỆU EURO 2012 ---

# Để code chạy được ngay mà không cần file,
# ta đọc dữ liệu trực tiếp từ 1 link online
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro_2012/Euro_2012_stats.csv'

# "Tạo data frame euro12" (Đọc file)
euro12 = pd.read_csv(url)
print("--- Đã đọc dữ liệu euro2012.csv ---")


# 1. In giá trị cột Goals
print("\n1. Giá trị cột 'Goals':")
print(euro12['Goals'])

# 2. Có bao nhiêu đội tham gia Euro2012?
# Lấy số hàng (mỗi hàng 1 đội)
num_teams = euro12.shape[0]
print(f"\n2. Số đội tham gia: {num_teams} đội")

# 3. In thông tin của Euro2012 (type, shape, danh sách cột)
print("\n3. Thông tin chung của Euro2012:")
print(f"   Kích thước (Shape): {euro12.shape}")
print(f"   Danh sách các cột: {euro12.columns.tolist()}")
print("   Thông tin chi tiết (Info):")
euro12.info()

# 4. Tạo 1 data frame mới discipline
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print("\n4. Data frame 'discipline' (5 dòng đầu):")
print(discipline.head())

# 5. Sắp xếp discipline
discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=False)
print("\n5. Discipline đã sắp xếp (Thẻ Đỏ, Thẻ Vàng giảm dần):")
print(discipline_sorted)

# 6. a) Tính trung bình Yellow Cards
avg_yellow_cards = euro12['Yellow Cards'].mean()
print(f"\n6. a) Số thẻ vàng trung bình: {avg_yellow_cards:.2f}")

# 6. b) Lọc các đội đã ghi hơn 6 bàn thắng
teams_over_6_goals = euro12[euro12['Goals'] > 6]
print("\n6. b) Các đội ghi hơn 6 bàn:")
print(teams_over_6_goals[['Team', 'Goals']])

# 7. In các đội mà tên bắt đầu bằng 'G'
teams_starting_G = euro12[euro12['Team'].str.startswith('G')]
print("\n7. Các đội có tên bắt đầu bằng 'G':")
print(teams_starting_G)

# 8. In 7 cột đầu của euro12
print("\n8. 7 cột đầu tiên (5 dòng đầu):")
print(euro12.iloc[:, :7].head())

# 9. In tất cả các cột, trừ 3 cột cuối
print("\n9. Tất cả các cột trừ 3 cột cuối (5 dòng đầu):")
print(euro12.iloc[:, :-3].head())

# 10. In các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards
selected_stats = euro12[['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']]
print("\n10. Các cột (Team, Goals, Shooting Accuracy, YC, RC):")
print(selected_stats)

# 11. In cột 'Team', 'Shooting Accuracy' của 'England', 'Italy', 'Russia'
teams_of_interest = ['England', 'Italy', 'Russia']
# Dùng .isin() để lọc các đội có trong list
result_11 = euro12[euro12['Team'].isin(teams_of_interest)]
print("\n11. Shooting Accuracy của Anh, Ý, Nga:")
print(result_11[['Team', 'Shooting Accuracy']])

HTTPError: HTTP Error 404: Not Found

In [1]:
import pandas as pd
import numpy as np

# --- BÀI 3.10: THỐNG KÊ DỮ LIỆU - GROUPBY ---

# Đọc file drinks.csv từ một link online
# (index_col=0: Dùng cột đầu tiên, 'country', làm chỉ mục)
try:
    url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/03_Grouping/Alcohol_Consumption/drinks.csv"
    
    # 1. Đọc dữ liệu, lưu vào biến 'drink'
    drink = pd.read_csv(url, index_col=0)
    print("--- 1. Đã đọc xong file 'drinks.csv' ---")

    # o Cho biết kiểu dữ liệu (type), kích thước (shape) của drink
    print("\nKiểu dữ liệu (dtypes):")
    print(drink.dtypes)
    print("\nKích thước (shape):", drink.shape)
    
    # o Hiển thị tên các cột (columns) của drink
    print("\nTên các cột (columns):", drink.columns.tolist())

    # o Xem 5 dòng dữ liệu đầu (head) và cuối (tail)
    print("\n5 dòng đầu (head):")
    print(drink.head())
    print("\n5 dòng cuối (tail):")
    print(drink.tail())
    
    # 2. Cho biết số lượng bia tiêu thụ trung bình ở mỗi châu lục
    print("\n--- 2. Lượng bia TB theo châu lục ---")
    # Ta nhóm theo 'continent', chọn cột 'beer_servings' và tính trung bình
    beer_mean = drink.groupby('continent')['beer_servings'].mean()
    print(beer_mean)

    # 3. Cho biết thông tin thống kê (describe) lượng rượu vang
    print("\n--- 3. Thống kê rượu vang theo châu lục ---")
    wine_stats = drink.groupby('continent')['wine_servings'].describe()
    print(wine_stats)

    # 4. Cho biết giá trị trung bình (mean), trung vị (median),
    # min, max của rượu mạnh (spirit_servings)
    print("\n--- 4. Thống kê rượu mạnh theo châu lục ---")
    spirit_agg = drink.groupby('continent')['spirit_servings'].agg(
        ['mean', 'median', 'min', 'max']
    )
    print(spirit_agg)
    
    # 5. Cho biết lượng (bia) trung bình lớn nhất ở châu lục
    print("\n--- 5. Châu lục uống bia TB nhiều nhất ---")
    # idxmax() tìm chỉ mục (tên châu lục) có giá trị lớn nhất
    print(f"Châu lục: {beer_mean.idxmax()}")
    print(f"Lượng TB: {beer_mean.max():.2f} servings")

    # 6. Sắp xếp dữ liệu (sort_values) theo lượng bia tiêu thụ
    print("\n--- 6. Sắp xếp theo lượng bia giảm dần (Top 5) ---")
    drink_sorted_by_beer = drink.sort_values(by='beer_servings', ascending=False)
    # In 5 dòng đầu của bảng đã sắp xếp
    print(drink_sorted_by_beer.head())

    # 7. Cho biết 5 quốc gia có lượng tiêu thụ bia nhiều nhất
    print("\n--- 7. 5 quốc gia uống bia nhiều nhất ---")
    # Dùng nlargest để lấy 5 giá trị lớn nhất
    top_5_beer = drink.nlargest(5, 'beer_servings')
    print(top_5_beer[['beer_servings']]) # Chỉ in cột bia

    # 8. Cho biết 5 quốc gia có lượng tiêu thụ bia ít nhất
    print("\n--- 8. 5 quốc gia uống bia ít nhất ---")
    # Dùng nsmallest để lấy 5 giá trị nhỏ nhất
    bottom_5_beer = drink.nsmallest(5, 'beer_servings')
    print(bottom_5_beer[['beer_servings']])

except Exception as e:
    print(f"\nLỖI: Không thể tải hoặc xử lý dữ liệu. {e}")
    print("Vui lòng kiểm tra kết nối Internet.")


LỖI: Không thể tải hoặc xử lý dữ liệu. HTTP Error 404: Not Found
Vui lòng kiểm tra kết nối Internet.


In [20]:
import pandas as pd
import numpy as np

# --- BÀI 3.11: GIAO DỊCH CHỨNG KHOÁN (ĐỌC FILE THẬT) ---

try:
    # 1. Đọc dữ liệu từ các file CSV
    stocks1 = pd.read_csv('stocks1.csv')
    stocks2 = pd.read_csv('stocks2.csv')
    companies = pd.read_csv('companies.csv')

    print("--- 1. Đã đọc thành công 3 file CSV ---")
    print("Thông tin stocks1:")
    stocks1.info()

    # 2. Xử lý Null trong stocks1 và stocks2
    print("\n--- 2. Xử lý giá trị Null ---")
    
    # Fill 'low' trong stocks1 bằng giá trị min của cột đó cho cùng mã 'symbol'
    # transform trả về một Series có cùng index với DataFrame gốc
    stocks1['low'] = stocks1.groupby('symbol')['low'].transform(lambda x: x.fillna(x.min()))
    
    # Fill 'high' trong stocks2 bằng giá trị max
    stocks2['high'] = stocks2.groupby('symbol')['high'].transform(lambda x: x.fillna(x.max()))
    print("Đã xử lý xong giá trị Null.")

    # 3. Gộp stocks1 và stocks2 thành stocks
    stocks = pd.concat([stocks1, stocks2], ignore_index=True)
    print("\n--- 3. Gộp stocks1 và stocks2 ---")
    print("DataFrame 'stocks' sau khi gộp:")
    print(stocks)

    # 4. Gộp stocks và companies thành stocks_companies
    stocks_companies = pd.merge(stocks, companies, left_on='symbol', right_on='name')
    print("\n--- 4. Gộp stocks và companies ---")
    print("5 dòng đầu của 'stocks_companies':")
    print(stocks_companies.head())

    # 5. Tính giá và volume trung bình của mỗi công ty
    print("\n--- 5. Giá trị trung bình theo công ty ---")
    cols_to_avg = ['open', 'high', 'low', 'close', 'volume']
    company_avg = stocks_companies.groupby('name')[cols_to_avg].mean()
    print(company_avg)

    # 6. Thống kê giá đóng cửa (close)
    print("\n--- 6. Thống kê giá 'close' theo công ty ---")
    close_stats = stocks_companies.groupby('name')['close'].agg(['mean', 'min', 'max'])
    print(close_stats)

    # 7. Tạo cột parsed_time
    stocks_companies['parsed_time'] = pd.to_datetime(stocks_companies['date'])
    print("\n--- 7. Đã tạo cột 'parsed_time' ---")
    print("Kiểu dữ liệu cột 'parsed_time':", stocks_companies['parsed_time'].dtype)

    # 8. Thêm cột result
    stocks_companies['result'] = np.where(stocks_companies['close'] > stocks_companies['open'], 'up', 'down')
    print("\n--- 8. Đã thêm cột 'result' ---")
    print(stocks_companies[['symbol', 'open', 'close', 'result']])

except FileNotFoundError:
    print("LỖI: Không tìm thấy file CSV. Vui lòng đảm bảo bạn đã tạo các file")
    print("'stocks1.csv', 'stocks2.csv', và 'companies.csv' trong cùng thư mục.")
except Exception as e:
    print(f"Đã xảy ra lỗi: {e}")

--- 1. Đã đọc thành công 3 file CSV ---
Thông tin stocks1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    4 non-null      object 
 1   symbol  4 non-null      object 
 2   open    4 non-null      int64  
 3   high    4 non-null      int64  
 4   low     3 non-null      float64
 5   close   4 non-null      int64  
 6   volume  4 non-null      int64  
dtypes: float64(1), int64(4), object(2)
memory usage: 356.0+ bytes

--- 2. Xử lý giá trị Null ---
Đã xử lý xong giá trị Null.

--- 3. Gộp stocks1 và stocks2 ---
DataFrame 'stocks' sau khi gộp:
         date symbol    open  high     low  close  volume
0  2020-01-01   AAPL   150.0   152   149.0    151  1000.0
1  2020-01-02   AAPL   151.0   153   150.0    152  1200.0
2  2020-01-01   MSFT   200.0   202   198.0    199   800.0
3  2020-01-02   MSFT   199.0   201   198.0    200   900.0
4  2020-01-03   AAPL   15

In [1]:
import pandas as pd

# ------------------------------------------------------------------
# ĐỊNH NGHĨA ĐƯỜNG DẪN
# Giả sử các tệp CSV nằm trong thư mục con 'ml-latest-small'
# ------------------------------------------------------------------
movies_path = 'ml-latest-small/movies.csv'
ratings_path = 'ml-latest-small/ratings.csv'
tags_path = 'ml-latest-small/tags.csv'

print("Bắt đầu quá trình phân tích dữ liệu MovieLens...")

# ------------------------------------------------------------------
# 1. Đọc dữ liệu & Data Structures
# ------------------------------------------------------------------
print("\n--- 1. Đọc dữ liệu & Data Structures ---")
try:
    # Đọc các tệp CSV vào DataFrame của pandas
    movies_df = pd.read_csv(movies_path)
    ratings_df = pd.read_csv(ratings_path)
    tags_df = pd.read_csv(tags_path)

    print("Đã đọc thành công 3 tệp CSV.")
    
    print("\nThông tin tệp 'movies.csv':")
    movies_df.info()
    print("\n5 dòng đầu tiên của 'movies.csv':")
    print(movies_df.head())

    print("\nThông tin tệp 'ratings.csv':")
    ratings_df.info()
    print("\n5 dòng đầu tiên của 'ratings.csv':")
    print(ratings_df.head())

except FileNotFoundError:
    print(f"LỖI: Không tìm thấy tệp.")
    print(f"Hãy chắc chắn rằng bạn đã giải nén tệp zip và")
    print(f"đường dẫn '{movies_path}' là chính xác.")
    # Thoát chương trình nếu không tìm thấy tệp
    exit()

# ------------------------------------------------------------------
# 2. Xử lý dữ liệu bị thiếu/không hợp lệ
# ------------------------------------------------------------------
print("\n--- 2. Xử lý dữ liệu bị thiếu/không hợp lệ ---")
# Kiểm tra xem có bao nhiêu giá trị bị thiếu (NaN) trong mỗi cột
print("Kiểm tra giá trị thiếu (NaN) trong 'movies_df':")
print(movies_df.isnull().sum())
print("\nKiểm tra giá trị thiếu (NaN) trong 'ratings_df':")
print(ratings_df.isnull().sum())

# Bộ dữ liệu này khá sạch. 
# Nếu có dữ liệu thiếu, chúng ta có thể xóa các hàng đó:
# movies_df = movies_df.dropna()
# ratings_df = ratings_df.dropna()
print("Bộ dữ liệu này không có giá trị nào bị thiếu.")

# ------------------------------------------------------------------
# 3. Gộp DataFrame
# ------------------------------------------------------------------
print("\n--- 3. Gộp DataFrame ---")
# Gộp (merge) ratings_df và movies_df dựa trên cột chung 'movieId'
merged_df = pd.merge(ratings_df, movies_df, on='movieId')

print("Đã gộp thành công 'ratings_df' và 'movies_df' dựa trên 'movieId'.")
print("5 dòng đầu tiên của DataFrame đã gộp:")
print(merged_df.head())

# ------------------------------------------------------------------
# 4. Lọc dữ liệu theo yêu cầu
# ------------------------------------------------------------------
print("\n--- 4. Lọc dữ liệu theo yêu cầu ---")
# Ví dụ: Lọc tất cả các đánh giá cho một bộ phim cụ thể, 
# ví dụ 'Forrest Gump (1994)' (có movieId = 356)
forrest_gump_ratings = merged_df[merged_df['title'] == 'Forrest Gump (1994)']
print(f"\nTìm thấy {len(forrest_gump_ratings)} đánh giá cho phim 'Forrest Gump (1994)':")
print(forrest_gump_ratings[['userId', 'rating', 'timestamp']].head())

# Ví dụ 2: Lọc tất cả các phim được đánh giá 5 sao
top_rated_movies = merged_df[merged_df['rating'] == 5.0]
print(f"\nTìm thấy {len(top_rated_movies)} lượt đánh giá 5 sao.")
print("Một số phim được đánh giá 5 sao:")
print(top_rated_movies[['title', 'genres', 'userId']].head())

# ------------------------------------------------------------------
# 5. Thống kê dữ liệu
# ------------------------------------------------------------------
print("\n--- 5. Thống kê dữ liệu ---")
# Thống kê mô tả chung cho cột 'rating' (điểm đánh giá)
print("Thống kê mô tả chung cho tất cả các đánh giá (cột 'rating'):")
print(merged_df['rating'].describe())

# Tính điểm trung bình và số lượng đánh giá cho mỗi phim
movie_stats = merged_df.groupby('title')['rating'].agg(['count', 'mean'])
movie_stats = movie_stats.rename(columns={'count': 'Số lượng đánh giá', 'mean': 'Điểm trung bình'})

# Sắp xếp theo điểm trung bình giảm dần
print("\nTop 10 phim có điểm trung bình cao nhất (với ít nhất 50 đánh giá):")
min_reviews = 50
high_rated_popular = movie_stats[movie_stats['Số lượng đánh giá'] >= min_reviews]
print(high_rated_popular.sort_values(by='Điểm trung bình', ascending=False).head(10))

# Sắp xếp theo số lượng đánh giá giảm dần
print("\nTop 10 phim được đánh giá nhiều nhất:")
print(movie_stats.sort_values(by='Số lượng đánh giá', ascending=False).head(10))

# ------------------------------------------------------------------
# 6. Parsing Timestamps
# ------------------------------------------------------------------
print("\n--- 6. Parsing Timestamps ---")
# Cột 'timestamp' hiện là một số nguyên (Unix timestamp)
print("Kiểu dữ liệu của cột 'timestamp' trước khi chuyển đổi:")
print(ratings_df['timestamp'].dtype)
print(ratings_df[['userId', 'timestamp']].head())

# Chuyển đổi timestamp (đơn vị là giây) sang đối tượng datetime
# Chúng ta sẽ tạo một cột mới tên là 'datetime'
ratings_df['datetime'] = pd.to_datetime(ratings_df['timestamp'], unit='s')
tags_df['datetime'] = pd.to_datetime(tags_df['timestamp'], unit='s')

print("\nĐã chuyển đổi 'timestamp' sang 'datetime' (trong ratings_df):")
print(ratings_df[['userId', 'timestamp', 'datetime']].head())

print("\nĐã chuyển đổi 'timestamp' sang 'datetime' (trong tags_df):")
print(tags_df[['userId', 'tag', 'datetime']].head())

print("\n--- Quá trình phân tích hoàn tất ---")

KeyboardInterrupt: 